### ISSUE TITLE
Unresolved import `self::inner`

### ISSUE THREAD

**Issue by ohmyarch** [WLBF/single-instance#4]
error[E0432]: unresolved import `self::inner`
  --> /home/xxx/.cargo/git/checkouts/single-instance-xxx/src/lib.rs:32:15
   |
32 | pub use self::inner::*;
   |               ^^^^^ maybe a missing crate `inner`?

single-instance version: git master
target: x86_64-pc-windows-gnu

single-instance 0.1.1 on crates.io is fine.

**Comment by WLBF** [comment]
fixed on master branch
