### ISSUE TITLE
macOS not listed as supported platform on docs.rs

### ISSUE THREAD

**Issue by qforce85** [WLBF/single-instance#5]
Hello,

according to the information over at [docs.rs](https://docs.rs/single-instance/0.1.2/single_instance/), this crate is supported on Windows 32-bit, Windows 64-bit and Linux 64-bit. However, the source code in v0.1.2 suggests that macOS is now also supported. So apparently the information on docs.rs needs to be updated to reflect this.

Best regards
q:-) <= Quang

**Comment by WLBF** [comment]
fixed on [latest version](https://docs.rs/single-instance/0.3.1/single_instance/index.html)
