### ISSUE TITLE
Consider using an abstract Unix domain socket on Linux

### ISSUE THREAD

**Issue by woodruffw** [WLBF/single-instance#6]
Hey there! I was looking into writing my own crate for process singletons, and I ran into this one. Nice work!

I'm just dropping in to offer a suggestion for improving this crate, at least on Linux: instead of acquiring a lock on a file, you could instead create a Unix domain socket in the ["abstract" namespace](https://man7.org/linux/man-pages/man7/unix.7.html). This has a few advantages:

* The abstract namespace never touches disk, meaning that you don't have to worry about filesystem permissions
* Unix domain sockets already have create-exclusive behavior, reducing the number of system calls
* Unix domain sockets are automatically collected on process destruction, meaning that you don't need a `Drop` (which won't fire on program interrupts or aborts)

The [nix](https://docs.rs/nix/0.19.1/nix/sys/socket/struct.UnixAddr.html#method.new_abstract) crate has support for creating domain sockets in the abstract namespace. I'd be happy to work on this feature, if you're interested.

**Comment by WLBF** [comment]
The advantages you listed seems very attactive. I think use abstract Unix domain socket instead of file would be a great idea.

**Comment by woodruffw** [comment]
Cool, I’ll give it a try this week.

**Comment by woodruffw** [comment]
#7.
