### ISSUE TITLE
SingleInstance is not Send on Windows platform

### ISSUE THREAD

**Issue by ancwrd1** [WLBF/single-instance#8]
When trying to use the `SingleInstance` on Windows in the concurrent or asynchronous context the compilation errors are raised about data structure being not `Send` (and eventually `Sync`):

```text
the trait `Send` is not implemented for `*mut c_void`
```

I think it is related to the internal implementation of single-instance. Would be nice if it's made `Send + Sync` explicitly on Windows.

On macOS and Linux this doesn't happen.

**Comment by WLBF** [comment]
SingleInstance is suppose to make process singleton. I dont think it should be used in the concurrent or asynchronous context.
